refactoring kbuild/kbuild.sh (WIP)

diff --git a/kbuild b/kbuild
--- a/kbuild
+++ b/kbuild
@@ -1,59 +1,101 @@
 #!/bin/bash
 ##===========================================================================
 #%
-#% USAGE: kbuild [options] [config file]
+#% USAGE: kbuild [OPTIONS] COMMAND
 #%
 #% The kbuild script is a convenient wrapper running the kbuild.sh script
 #% inside a Docker container.
 #%
-#% If no configuration file is passed as argument is given, it looks for a 
-#% file named kbuild.cfg in curernt directory.
+#% If no configuration file is specified, it looks for a file named
+#% kbuild.cfg in current directory.
+#%
+#%
+#% COMMANDS:
+#%   all              Builds everything specified in the CONFIG_FILE file
+#%   linux            Only build Linux Debian packages
+#%   rtl8723          Only build RTL8723 Wifi drivers packages
+#%   chip-mali        Only build Mali GPU drivers for C.H.I.P 
+#%
+#%   linux-nconfig    Allows to modify the Linux configuration
+#%
+#%   shell <CMD>      Run interactive bash shell in Docker container
+#%   update-image     Tries to pull the lates version of the Docker image
+#%
 #%
 #% OPTIONS:
-#%   -h             Show this help
-#%   -v             Show verbose output
-#%   -c CMD         Run custom command in Docker container
-#%   -i IMAGE       Use custom command in Docker container image
-#%   -s             Run interactive bash shell in Docker container
+#%   -h               Show this help
+#%   -v               Show verbose output
+#%   -c CONFIG_FILE   Use custom config file
+#%   -i IMAGE         Use custom command in Docker container image
 #%
 ##===========================================================================
 
-SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+export SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 [[ ! -x "$(which docker)" ]] && echo "ERROR: cannot find docker binay in path - please verify Docker installation" && exit 1
 
-CMD=kbuild.sh
+function help() {
+    head -n 200 "$SCRIPT_DIR/$(basename $0)" | sed -n -e 's/^#%//gp;'
+    exit
+}
 
-while getopts ":hvsc:" opt; do
+while getopts ":hvi:c:" opt; do
     case $opt in
         h)
-            head -n 200 "$SCRIPT_DIR/$(basename $0)" | sed -n -e 's/^#%//gp;'
-            exit
+            help
             ;;
         v)
             export VERBOSE_FLAG="-v"
             ;;
         c)
-            CMD="${OPTARG}"
+            CONFIG_FILE="${OPTARG}"
             ;;
-        s)
-            CMD=""
+        i)
+            CONTAINER_IMAGE="${OPTARG}"
             ;;
  
         \?)
             echo "invalid option: -$OPTARG"
+            exit 1
             ;;
     esac
 done
 shift "$((OPTIND - 1))"
 
-export SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-export CONTAINER_IMAGE=${CONTAINER_IMAGE:-ntc-registry.githost.io/nextthingco/kbuild:unstable}
+command="$1"
+case "$command" in
+    linux-nconfig)
+        ### do something special here!
+        CMDLINE_ARGS="$command"
+        ;;
+
+    shell)
+            CMD="${@}"
+            CMD="${CMD#* }"
+            CMD=${CMD:-"/bin/bash --login"}
+        ;;
+
+    update-image)
+        echo "ERROR: not implemented yet - sorry"
+        exit 1
+        ;;
+
+    "")
+        help
+        ;;
+
+    *)
+        CMDLINE_ARGS="$command"
+        ;;
+esac
+
+
+export CMD="${CMD:-kbuild.sh $VERBOSE_FLAG $CMDLINE_ARGS}"
+export CONTAINER_IMAGE="${CONTAINER_IMAGE:-ntc-registry.githost.io/nextthingco/kbuild:unstable}"
 
 export CI_JOB_ID=${RANDOM}
 
 # CONFIG_FILE either spacified as environment variable or as first command line parameter
-CONFIG_FILE=${CONFIG_FILE:-$1}
 CONFIG_FILE=${CONFIG_FILE:-kbuild.cfg}
 [[ ! -f "$CONFIG_FILE" ]] && echo "ERROR: cannot find configuration file '$CONFIG_FILE'" && exit 1
 TMP_CFG=$(mktemp)
@@ -67,7 +109,6 @@ docker run --rm -it \
            -v $SCRIPT_DIR:/opt/kbuild \
            -v $PWD:/work -w /work \
            $CFG_FILE_FLAG \
-           $VERBOSE_FLAG \
-           $CONTAINER_IMAGE bash -c "$CMD"
+           $CONTAINER_IMAGE $CMD
 
 rm $TMP_CFG
